### ISSUE TITLE
The Agent properties links to the Classes properties

### ISSUE THREAD

**Issue by JBPressac** [RDARegistry/www.rdaregistry.info#1]
Hello,
The links to the RDF serializations in the Agent properties page (http://www.rdaregistry.info/Elements/a/) links to the Class properties. For instance, the Turtle (text/turtle) links to https://raw2.github.com/RDARegistry/RDA-Vocabularies/master/ttl/Elements/c.ttl instead of https://raw2.github.com/RDARegistry/RDA-Vocabularies/master/ttl/Elements/a.ttl ...

**Comment by jonphipps** [comment]
Good catch! Thanks. Fixed.
