### ISSUE TITLE
typo in http://www.rdaregistry.info/Maps/mapMRC2RDA.html

### ISSUE THREAD

**Issue by krugar** [RDARegistry/www.rdaregistry.info#2]
hi,
obviously the page is no longer developed here, but this still seemed to be the most fitting place to report an error that is not in the vocabularies themselves, but in the website text. i hope someone notices this here

from http://www.rdaregistry.info/Maps/mapMRC2RDA.html right-hand text field, lower half:

> skos:broadMatch is used rather than skos:exactMatch because there is no formal alignment between RDA and the MARC code list. This looser mapping can be augmented by skos:exactMatch at any point in the future without deprecation because skos:exactMatch is a sub-property of skos:closeMatch. skos:broadMatch is used for mrc:cng ("Cinematographer") and mrc:vdg ("Videographer") because they are narrower in scope that rdau:P60452 (designator "director of photography").

the first mention of *skos:broadMatch* is likely meant to be *skos:closeMatch* instead.

**Comment by GordonDunsire** [comment]
Thanks for the catch!

The typo has been fixed (and on the page for the inverse map).
